src/Presentation/FmsWebUI/Controllers/LookupController.cs
using ApplicationFMS.Handlers.Feedbacks.Queries.GetPublicFeedbackDetail;
using ApplicationFMS.Handlers.LookUp.LookupCompany;
using ApplicationFMS.Handlers.LookUp.LookUpCountry;
using ApplicationFMS.Handlers.LookUp.LookupEducation;
using ApplicationFMS.Handlers.LookUp.LookupFeedbackType;
using ApplicationFMS.Handlers.LookUp.LookupProduct;
using ApplicationFMS.Handlers.LookUp.LookupSector;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace FmsWebUI.Controllers
{
    public class LookupController : BaseController
    {
        public async Task<IActionResult> Sector()
        {
            var response = await Mediator.Send(new LookupSectorListQuery());
            return Ok(response.List);
        }
        
        public async Task<IActionResult> Company(int id)
        {
            var response = await Mediator.Send(new LookupCompanyListQuery { SectorId = id });
            return Ok(response.List);
        }

        public async Task<IActionResult> Product(int id)
        {
            var response = await Mediator.Send(new LookupProductListQuery { CompanyId = id });
            return Ok(response.List);
        }

        public async Task<IActionResult> Type()
        {
            var response = await Mediator.Send(new LookupFeedbackTypeListQuery());
            return Ok(response.List);
        }

        public async Task<IActionResult> Education()
        {
            var response = await Mediator.Send(new LookupEducationListQuery());
            return Ok(response.List);
        }

        public async Task<IActionResult> City()
        {
            var response = await Mediator.Send(new LookupCityListQuery());
            return Ok(response.CityList);
        }

    }
}

src/Presentation/FmsWebUI/Controllers/UserController.cs
using ApplicationFMS.Handlers.Account.Commands.RegisterUser;
using ApplicationFMS.Handlers.Account.Commands.VerifyEmail;
using ApplicationFMS.Handlers.Account.Queries.UserLogin;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace FmsWebUI.Controllers
{
    public class UserController : BaseController
    {


        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserLoginQuery request)
        {
            var response = await MediateWithoutException(request);
            if (response.Meta.SuccessStatus)
            {
                HttpContext.Response.Cookies.Append("Authorization", response.data.ToString(), new CookieOptions { HttpOnly = true });
                return RedirectToAction("List", "Feedback");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {

            return View();
        }

        [HttpGet]
        public IActionResult LogOut()
        {
            Response.Cookies.Delete("Authorization");
            return RedirectToAction("Login");
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterUserCommand request)
        {
            var response = await MediateWithoutException(request);
            if (response.Meta.SuccessStatus)
                return RedirectToAction("Verify");
            return View();
        }

        [HttpGet]
        public IActionResult Verify()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Verify(VerifyEmailCommand request)
        {
            var response = await MediateWithoutException(request);
            if (response.Meta.SuccessStatus)
            {
                return RedirectToAction("Verified");
            }
            return View();
        }

        [HttpGet]
        public IActionResult VerifyFromMail(string email, string verificationCode)
        {
            var response = MediateWithoutException(new VerifyEmailCommand() { Email = email, VerificationCode = verificationCode }).Result;
            if (response.Meta.SuccessStatus)
            {
                return RedirectToAction("Verified");
            }
            else
            {
                return RedirectToAction("Verify");
            }
        }

        [HttpGet]
        public IActionResult Verified()
        {

            return View();
        }

    }
}

src/Presentation/FmsWebUI/Views/User/Login.cshtml
@model ApplicationFMS.Handlers.Account.Queries.UserLogin.UserLoginQuery


@{
    ViewData["Title"] = "Giriş Yap";
}

<div class="row justify-content-center">
<div class="d-flex col-lg-4 align-items-center auth-bg px-2 p-lg-5">
    <div class="col-12 col-sm-8 col-md-6 col-lg-12 px-xl-2 mx-auto">
        <h2 class="card-title fw-bold mb-1">FMS Sistemine Hoşgeldiniz!</h2>
        <p class="card-text mb-2"></p>

        <form class="form" enctype="application/json" asp-controller="User" asp-action="Login" method="POST" novalidate="novalidate">
            <div class="mb-1">
                <label class="form-label" for="login-email">Email</label>
                <input asp-for="Email" class="form-control" type="text"  placeholder="john@example.com" >
            </div>

            <div class="mb-1">
                <div class="d-flex justify-content-between">
                    <label class="form-label" for="login-password">Parola</label>

                </div>
                <div class="input-group">
                    <input asp-for="Password" class="form-control"  type="password"  placeholder="············" >

                </div>
            </div>
            <div class="mb-1">

            </div>
            <button class="btn btn-primary w-100 waves-effect waves-float waves-light" tabindex="4">Giriş Yap</button>
        </form>
        <p class="text-center mt-2"><span>Henüz bir FMS hesabınız yok mu?</span><a asp-action="Register"><span>Hemen yeni bir hesap oluşturun!</span></a></p>
    </div>
</div>
</div>

src/Presentation/FmsWebUI/Views/User/Logout.cshtml
@model ApplicationFMS.Handlers.Account.Queries.UserLogin.UserLoginQuery


@{
    ViewData["Title"] = "Çıkış Yap";
}

<div class="row justify-content-center">
<div class="d-flex col-lg-4 align-items-center auth-bg px-2 p-lg-5">
    <div class="col-12 col-sm-8 col-md-6 col-lg-12 px-xl-2 mx-auto">
        <h2 class="card-title fw-bold mb-1">FMS Sistemine Hoşgeldiniz!</h2>
        <p class="card-text mb-2"></p>

        <form class="form" enctype="application/json" asp-controller="User" asp-action="Login" method="POST" novalidate="novalidate">
            <div class="mb-1">
                <label class="form-label" for="login-email">Email</label>
                <input asp-for="Email" class="form-control" id="login-email" type="text" name="login-email" placeholder="john@example.com" aria-describedby="login-email" autofocus="" tabindex="1">
            </div>

            <div class="mb-1">
                <div class="d-flex justify-content-between">
                    <label class="form-label" for="login-password">Parola</label>

                </div>
                <div class="input-group">
                    <input asp-for="Password" class="form-control"  type="password"  placeholder="············" >

                </div>
            </div>
            <div class="mb-1">

            </div>
            <button class="btn btn-primary w-100 waves-effect waves-float waves-light" tabindex="4">Doğrula</button>
        </form>
        <p class="text-center mt-2"><span>Henüz bir FMS hesabınız yok mu?</span><a asp-action="Register"><span>Hemen yeni bir hesap oluşturun!</span></a></p>
    </div>
</div>
</div>

src/Presentation/FmsWebUI/Views/User/Register.cshtml
@model ApplicationFMS.Handlers.Account.Commands.RegisterUser.RegisterUserCommand
@{
    ViewData["Title"] = "Kullanıcı Kayıt";
}



<section id="multiple-column-form">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Yeni Kullanıcı</h4>
                </div>
                <div class="card-body">
                    <form class="form" method="post" enctype="application/json" asp-controller="User" asp-action="Register">
                        <div class="row">

                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="first-name-column">Ad</label>
                                    <input id="first-name-column" class="form-control" placeholder="Ad" asp-for="FirstName">
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="last-name-column">Soyad</label>
                                    <input id="last-name-column" class="form-control" placeholder="Soyad" asp-for="LastName">
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="email-id-column">E-Posta</label>
                                    <input type="email" id="email-id-column" class="form-control" placeholder="E-Posta" asp-for="Email">
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label">Parola</label>
                                    <input type="password" class="form-control" placeholder="Parola" asp-for="Password">
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label"> Telefon Numarası</label>
                                    <input type="hidden" class="form-control" asp-for="PhoneCode" value="90">
                                    <input type="text" id="city-column" class="form-control" placeholder="Telefon Numarası" asp-for="Phone">
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label">Doğum Tarihi</label>
                                    <input type="datetime" class="form-control" placeholder="Doğum Tarihi" asp-for="BirthDate">
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label">Öğrenim Durumu</label>
                                    
                                    <select type="text" class="form-control" id="educationSelector" asp-for="EducationId">
                                        <option>---Öğrenim Durumu Seçiniz---</option>
                                    </select>
                                </div>
                            </div>
                            
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label">Şehir</label>
                                    <select type="text" class="form-control" id="citySelector" asp-for="CityId">
                                        <option>---Şehir Seçiniz---</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label">Rol</label>
                                    <input type="hidden" class="form-control" asp-for="RoleId" value="2">
                                    <input type="text" disabled="true" class="form-control" value="Müşteri" asp-for="RoleId">
                                </div>
                            </div>


                            <div class="col-12">
                                <button type="submit" class="btn btn-primary me-1 waves-effect waves-float waves-light">Kayıt Ol</button>
                                <button type="reset" class="btn btn-outline-secondary waves-effect">Formu Temizle</button>
                            </div>
                        </div>
                    </form>
                    <p class="text-center mt-2"><span>Zaten bir hesabınız var mı?</span><a asp-action="Login"><span>Hemen sisteme giriş yapın.</span></a></p>
                     

                </div>
            </div>
        </div>
    </div>
</section>


@section Scripts{

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            url: '@Url.Action("Education", "Lookup")',
            type: "GET",
            success: function (json, textStatus) {
                json = json || {};
                for (var i = 0; i < json.length; i++) {
                    $("#educationSelector").append(`<option value="${json[i].id}">${json[i].name}</option>`);
                }
            },
            error: function () {
                alert("Data Not Found");
            }
        });
    });

    $(document).ready(function () {
        $.ajax({
            url: '@Url.Action("City", "Lookup")',
            type: "GET",
            success: function (json, textStatus) {
                json = json || {};
                for (var i = 0; i < json.length; i++) {
                    $("#citySelector").append(`<option value="${json[i].id}">${json[i].cityName}</option>`);
                }
            },
            error: function () {
                alert("Data Not Found");
            }
        });
    });

    $(document).ready(function () {
        $("#selectCompany").prop("disabled", true);
        $("#selectSector").change(function () {
            var id = $("#selectSector").val();
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("Company", "Lookup")',
                data: { "id": id },
                success: function (json, textStatus) {
                    $("#selectCompany").empty();
                    $("#selectCompany").append(`<option value="">---Şirket Seçiniz---</option>`);
                    json = json || {};
                    for (var i = 0; i < json.length; i++) {
                        $("#selectCompany").append(`<option value="${json[i].id}">${json[i].name}</option>`);
                    }
                    $("#selectCompany").prop("disabled", false);
                },
                error: function () {
                    alert("Data Not Found");
                }
            });
        });
    });

    $(document).ready(function () {
        $("#selectProduct").prop("disabled", true);
        $("#selectCompany").change(function () {
            var id = $("#selectCompany").val();
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("Product", "Lookup")',
                data: { "id": id },
                success: function (json, textStatus) {
                    $("#selectProduct").empty();
                    $("#selectProduct").append(`<option value="">---Ürün Seçiniz---</option>`);
                    json = json || {};
                    for (var i = 0; i < json.length; i++) {
                        $("#selectProduct").append(`<option value="${json[i].id}">${json[i].name}</option>`);
                    }
                    $("#selectProduct").prop("disabled", false);
                },
                error: function () {
                    alert("Data Not Found");
                }
            });
        });
    });

</script>





}

src/Presentation/FmsWebUI/Views/User/Verified.cshtml
@{
    ViewData["Title"] = "E-posta Doğrulandı";
}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                
            </div>
            <div class="card-body">
                <h4 class=" text-center">FMS'e olan ilginiz için teşekkür ederiz.</h4>
                <p class="text-center mt-2"><span>E-posta adresiniz doğrulanmıştır.</span><a asp-action="Login"><span>Sisteme giriş yapabilirsiniz.</span></a></p>


            </div>
        </div>
    </div>
</div>

src/Presentation/FmsWebUI/Views/User/Verify.cshtml
@model ApplicationFMS.Handlers.Account.Commands.VerifyEmail.VerifyEmailCommand


@{
    ViewData["Title"] = "E-posta Doğrula";
}

<div class="row justify-content-center">


<div class="d-flex col-lg-4 align-items-center  px-2 p-lg-5">
                <div class="col-12 col-sm-8 col-md-6 col-lg-12 px-xl-2 mx-auto">
                  <h2 class="card-title fw-bold mb-1">FMS Sistemine Hoşgeldiniz!</h2>
                    <p class="card-text mb-2">Lütfen e-posta hesabınıza gönderilmiş olan bağlantıyı açın ya da aşağıdaki alana doğrulama kodunu giriniz.</p>

                  <form class="form" enctype="application/json" asp-controller="User" asp-action="Verify" method="POST" novalidate="novalidate">
                      <div class="mb-1">
                          <label class="form-label" for="login-email">Email</label>
                          <input asp-for="Email" class="form-control" id="login-email" type="email" placeholder="john@example.com" aria-describedby="login-email" autofocus="" tabindex="1">
                      </div>

                    <div class="mb-1">
                      <div class="d-flex justify-content-between">
                          <label class="form-label" for="login-password">Doğrulama Kodu</label>

                      </div>
                      <div class="input-group input-group-merge form-password-toggle">
                          <input asp-for="VerificationCode" class="form-control"  type="text" placeholder="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" >

                      </div>
                    </div>
                    <div class="mb-1">

                    </div>
                    <button class="btn btn-primary w-100 waves-effect waves-float waves-light" tabindex="4">Doğrula</button>
                  </form>
                  <p class="text-center mt-2"><span>Henüz bir FMS hesabınız yok mu?</span><a asp-action="Register"><span>Hemen yeni bir hesap oluşturun!</span></a></p>
                 </div>
              </div>
              
</div>