src/Presentation/FmsWebUI/Controllers/FeedbackController.cs
using ApplicationFMS.Handlers.Feedbacks.Queries.GetPublicFeedbackDetail;
using ApplicationFMS.Handlers.Feedbacks.Queries.GetPublicFeedbackList;
using ApplicationFMS.Helpers;
using FmsWebUI.Helper;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ApplicationFMS.Handlers.Feedbacks.Commands.DeleteFeedback;
using ApplicationFMS.Handlers.Feedbacks.Commands.ToggleSolved;
using ApplicationFMS.Handlers.Feedbacks.Commands.UpsertFeedback;
using AutoMapper;
using ApplicationFMS.Handlers.Reactions.Commands.ReactFeedback;
using ApplicationFMS.Handlers.Reactions.Commands.DeleteFeedbackReaction;
using CoreFMS.Entities;
using ApplicationFMS.Models;

namespace FmsWebUI.Controllers
{

    public class FeedbackController : BaseController
    {

        private readonly IMapper _mapper;
        public FeedbackController(IMapper mapper)
        {
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> GetDetail(int id)
        {
            var response = await Mediate(new GetPublicFeedbackDetailQuery { Id = id });
            return View((GetPublicFeedbackDetailVm)response.data);
        }


        [HttpGet]
        public ActionResult List(int? userId)
        {
            return View(new GetFeedbackListQuery{UserId = userId});
        }


        [HttpPost]
        public async Task<IActionResult> LoadFeedback([FromBody] GetFeedbackListQuery request)
        {
            var response = await MediateWithoutException(request);

            if (!response.Meta.SuccessStatus) return Unauthorized( TempData["Message"] );

            var feedbackList = (FeedbackListVm)response.data;
            TempData["filteredCountString"] = feedbackList.FilteredCount;
            return ViewComponent("MultipleFeedback", feedbackList);
        }

        [HttpGet]
        [Authorize(Constants.CustomerRole)]
        public async Task<IActionResult> Upsert(int? id)
        {
            var feedbackDetail = new GetPublicFeedbackDetailVm();
            if (id > 0)
            {
                feedbackDetail = (GetPublicFeedbackDetailVm)(await Mediate(new GetPublicFeedbackDetailQuery { Id = (int)id })).data;
            }
            var command = _mapper.Map<UpsertFeedbackCommand>(feedbackDetail);
            return View(command);
        }

        [HttpPost]
        [Authorize(Constants.CustomerRole)]
        public async Task<IActionResult> Upsert(UpsertFeedbackCommand command)
        {
            var response = await Mediate(command);
            if (response.Meta.SuccessStatus)
                return RedirectToAction("List");
            return View(command);
        }

        [HttpGet]
        [Authorize(Constants.CustomerRole)]
        public async Task<IActionResult> ToggleSolved(int id)
        {
            var response = await Mediate(new ToggleSolvedFeedbackCommand { Id = id });
            if (response.Meta.SuccessStatus)
                return RedirectToAction("GetDetail", new { id = id });
            return RedirectToAction("List");
        }

        [HttpGet]
        [Authorize(Constants.CustomerRole)]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await Mediate(new DeleteFeedbackCommand { Id = id });
            if (response.Meta.SuccessStatus)
                return RedirectToAction("List");
            return View();
        }

        [HttpGet]
        [Authorize(Constants.CustomerRole)]
        public async Task<IActionResult> React(int feedbackId, bool sentiment)
        {
            var response = await Mediate(new ReactFeedbackCommand { FeedbackId = feedbackId, Sentiment = sentiment });
            return RedirectToAction("GetDetail", new { id = feedbackId });
        }

        [HttpGet]
        [Authorize(Constants.CustomerRole)]
        public async Task<IActionResult> DeleteReaction(int feedbackId, bool sentiment)
        {
            var response = await Mediate(new DeleteFeedbackReactionCommand { FeedbackId = feedbackId });
            return RedirectToAction("GetDetail", new { id = feedbackId });
        }

    }
}

src/Presentation/FmsWebUI/Controllers/LookupController.cs
using ApplicationFMS.Handlers.Feedbacks.Queries.GetPublicFeedbackDetail;
using ApplicationFMS.Handlers.LookUp.LookupCompany;
using ApplicationFMS.Handlers.LookUp.LookUpCountry;
using ApplicationFMS.Handlers.LookUp.LookupEducation;
using ApplicationFMS.Handlers.LookUp.LookupFeedbackType;
using ApplicationFMS.Handlers.LookUp.LookupProduct;
using ApplicationFMS.Handlers.LookUp.LookupSector;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace FmsWebUI.Controllers
{
    public class LookupController : BaseController
    {
        public async Task<IActionResult> Sector()
        {
            var response = await Mediator.Send(new LookupSectorListQuery());
            return Ok(response.List);
        }
        
        public async Task<IActionResult> Company(int id)
        {
            var response = await Mediator.Send(new LookupCompanyListQuery { SectorId = id });
            return Ok(response.List);
        }

        public async Task<IActionResult> Product(int id)
        {
            var response = await Mediator.Send(new LookupProductListQuery { CompanyId = id });
            return Ok(response.List);
        }

        public async Task<IActionResult> Type()
        {
            var response = await Mediator.Send(new LookupFeedbackTypeListQuery());
            return Ok(response.List);
        }

        public async Task<IActionResult> Education()
        {
            var response = await Mediator.Send(new LookupEducationListQuery());
            return Ok(response.List);
        }

        public async Task<IActionResult> City()
        {
            var response = await Mediator.Send(new LookupCityListQuery());
            return Ok(response.CityList);
        }

    }
}

src/Presentation/FmsWebUI/Views/Feedback/GetDetail.cshtml
@using ApplicationFMS.Handlers.Feedbacks.Queries.GetPublicFeedbackDetail
@model ApplicationFMS.Handlers.Feedbacks.Queries.GetPublicFeedbackDetail.GetPublicFeedbackDetailVm
@{
    ViewData["Title"] = "Feedback Detail";
    ViewData["Breadcrumb"] = "GERİBİLDİRİM DETAYI";
    ViewData["OgUrl"] = "http://fms.uluoglakci.com/Feedback/GetDetail/" + @Model.Id;
    ViewData["FeedbackTitle"] = @Model.Title;
}


<div class="row match-height">


    <div class="card col-12">
        @if (Model.IsMine)
        {



            <div class="d-flex justify-content-around my-2 pt-30">

                <a type="button" class=" btn btn-outline-warning ms-1" style="display: inline-block;" onclick="@("window.location.href='" + @Url.Action("Upsert", "Feedback", new { id = @Model.Id }) + "'");">

                    <i class="fas fa-pencil-alt"></i>
                </a>

                @if (Model.IsSolved == false)
                {
                    <a type="button" class="swal2-cancel btn btn-outline-success ms-1" style="display: inline-block;" data-toggle="modal" data-target="#toggleCheckedModal">
                        <i class="fas fa-check"></i>
                    </a>
                }
                else
                {
                    <a type="button" class="swal2-cancel btn btn-relief-success ms-1" style="display: inline-block;" data-toggle="modal" data-target="#toggleCheckedModal">
                        <i class="fas fa-check"></i>
                    </a>
                }


                <button type="button" class="swal2-cancel btn btn-outline-danger ms-1" style="display: inline-block;" data-toggle="modal" data-target="#deleteModal">
                    <i class="fas fa-trash-alt"></i>
                </button>

            </div>

            <!-- Modal for Toggle Checked -->
            <div class="modal fade" id="toggleCheckedModal" tabindex="-1" aria-labelledby="toggleCheckedModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="toggleCheckedModalLabel">Geribildiriminize işlem yapıldı mı?</h5>
                            <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">X</button>
                        </div>
                        <div class="modal-body">
                            Onalarsanız, geribildiriminiz çözülme durumuna ilişkin etiket değiştirilecektir.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                            <button type="button" class="btn btn-primary" onclick="@("window.location.href='" + @Url.Action("ToggleSolved", "Feedback", new { id = @Model.Id }) + "'");">Onayla</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal for Delete -->
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Geribildiriminiz silinsin mi?</h5>
                            <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">X</button>
                        </div>
                        <div class="modal-body">
                            Onalarsanız, geribildiriminiz silinecektir.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                            <button type="button" class="btn btn-danger" onclick="@("window.location.href='" + @Url.Action("Delete", "Feedback", new { id = @Model.Id }) + "'");">Sil</button>
                        </div>
                    </div>
                </div>
            </div>
        }



    </div>

    <div class="col-lg-4 col-md-6 col-12">
        <div class="card">
            <div class="card-body">
                @await Component.InvokeAsync("SingleFeedbackInner", @Model)
                <div class="d-flex justify-content-around my-2 pt-75">
                    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="medium" data-text="Arkadaşlar, şu geribildirime bakar mısınız: '@Model.Title' İnanılmaz!!!" data-url="http://fms.uluoglakci.com/Feedback/GetDetail/@Model.Id" data-hashtags="FMS" data-dnt="true" data-show-count="false">Tweet</a>
                    <div class="fb-share-button"
                         data-href="http://fms.uluoglakci.com/Feedback/GetDetail/@Model.Id"
                         data-layout="button_count">
                    </div>
                </div>
            </div>
        </div>
    </div>





    <div class="col-lg-8 col-md-6 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Firmanın Cevapları</h4>

            </div>
            <div class="card-content collapse show" aria-expanded="true">
                <div class="card-body">
                    @if (Model.ReplyList.Count > 0)
                    {
                        foreach (ReplyDto reply in Model.ReplyList)
                        {
                            <p class="card-text font-weight-bolder">
                                @reply.UserName @(reply?.CompanyName != null ? ( "(" + reply.CompanyName + ")") : string.Empty)
                            </p>
                            <small class="text-muted">Gönderim Zamanı: @reply.CreatedAt</small>
                            <p class="card-text">@reply.Text</p>
                            <br />
                        }
                    }
                    else
                    {
                        <p class="card-text">Henüz cevap yok.</p>
                    }
                </div>
            </div>

        </div>
    </div>

</div>



<div class="col-lg-12 col-md-12 col-12">
    <div class="card card-user-timeline">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list user-timeline-title-icon"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></svg>
                <h4 class="card-title"> Yorumlar</h4>
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-vertical font-medium-3 cursor-pointer"><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>
        </div>
        <div class="card-body">
            <ul class="timeline ms-50">
                @if (Model.CommentList.Count > 0)
                {
                    foreach (var commentDto in Model.CommentList)
                    {
                        if (commentDto.IsActive)
                        {
                            @await Component.InvokeAsync("SingleComment", commentDto)
                        }
                    }

                }
                else
                {
                    <p class="card-text">Henüz yorum yok.</p>
                }

            </ul>
        </div>
    </div>
</div>


@section CustomScripts{
<!-- Load Facebook SDK for JavaScript -->
<div id="fb-root"></div>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
}


@section Scripts{
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
}

src/Presentation/FmsWebUI/Views/Feedback/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>WebUI feedback test</h1>

src/Presentation/FmsWebUI/Views/Feedback/SingleFeedback.cshtml
@model ApplicationFMS.Handlers.Feedbacks.Queries.GetPublicFeedbackList.PublicFeedbackDTO

    <div class="col-lg-4 col-md-6 col-12">
        <div class="card card-apply-job">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-1">
                    <div class="d-flex flex-row">
                        <div class="avatar me-1">
                            <img src="../../Content/images/portrait/small/user.png" alt="Avatar" width="42" height="42">
                        </div>
                        <div class="user-info">
                            <h5 class="mb-0">@Model.CustomerFirstName</h5>
                            <small class="text-muted">Gönderim Zamanı: @Model.CreatedAt</small>
                        </div>
                    </div>
                    <span class="badge rounded-pill badge-light-primary">@Model.TypeName</span>
                </div>
                <h4 class="apply-job-title">@Model.Title</h4>
                <p class="card-text mb-2">
                    @Model.Text
                </p>
                <div class="d-flex justify-content-around my-2 pt-75">

                    <button type="button" class="swal2-confirm btn btn-primary" aria-label="Thumbs up, great!" style="display: inline-block; " onclick="@("window.location.href='" + @Url.Action("Index", "Home", new { id = "0" }) + "'");">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up font-medium-1 me-50">
                            <path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3">

                            </path>
                        </svg>@Model.LikeCount
                    </button>

                    <button type="button" class="swal2-cancel btn btn-outline-danger ms-1" aria-label="Thumbs down" style="display: inline-block; " onclick="@("window.location.href='" + @Url.Action("Index", "Home", new { id = "0" }) + "'");">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-down font-medium-1">
                            <path d="M10 15v4a3 3 0 0 0 3 3l4-9V2H5.72a2 2 0 0 0-2 1.7l-1.38 9a2 2 0 0 0 2 2.3zm7-13h2.67A2.31 2.31 0 0 1 22 4v7a2.31 2.31 0 0 1-2.33 2H17"></path>
                        </svg>@Model.DislikeCount
                    </button>

                </div>


                <div class="col-12">
                    <button type="button" class="btn btn-primary waves-effect waves-float waves-light col-12" , onclick="@("window.location.href='" + @Url.Action("Index", "Home", new { id = "0" }) + "'");">
                        Yorum Yap!
                    </button>
                </div>
            </div>
        </div>
    </div>

src/Presentation/FmsWebUI/Views/Feedback/Upsert.cshtml
@model ApplicationFMS.Handlers.Feedbacks.Commands.UpsertFeedback.UpsertFeedbackCommand
@{
    ViewData["Title"] = "Upsert Feedback";
    ViewData["Breadcrumb"] = "GERİBİLDİRİM GÖNDER / DÜZENLE";
}

<section id="multiple-column-form">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Geribildirim Gönder</h4>

                </div>
                <div style="">
                    <div class="card-body">
                        <form class="form" id="feedbackSearchForm" method="post" asp-action="Upsert">
                            <div class="row">

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="basicSelect">Geribildirim Türü</label>
                                        <select class="form-control" asp-for="TypeId" id="selectType">
                                            <option value="">---Tür Seçiniz---</option>
                                            <option value="1">Şikayet</option>
                                            <option value="2">Öneri</option>
                                            <option value="3">Memnuniyet</option>
                                        </select>

                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="basicSelect">Şikayet Türü</label>
                                        <select class="form-control" asp-for="SubTypeId" id="selectSubType">
                                            <option value="">---Tür Seçiniz---</option>
                                            <option value="1">Arızalı</option>
                                            <option value="2">Sağlığa zararlı</option>
                                            <option value="3">Diğer</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label" for="basicSelect">Kullanıcı Adı</label>
                                        <select class="form-control" asp-for="IsAnonym" id="isAnonym">
                                            <option value="false">Belirtilmiş</option>
                                            <option value="true">Anonim</option>
                                        </select>
                                    </div>
                                </div>

                                @if (!(Model.TypeId > 0))
                                {
                                    <div class="col-md-6 col-12">
                                        <div class="mb-1">
                                            <label class="form-label" for="basicSelect">Sektör</label>

                                            <input id="sectorId" type="hidden" name="sectorId" />
                                            <select class="form-control" asp-items=@ViewBag.Sectors id="selectSector">
                                                <option value="">---Sektör Seçiniz---</option>
                                            </select>

                                        </div>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <div class="mb-1">
                                            <label class="form-label" for="basicSelect">Şirket</label>

                                            <input id="companyId" type="hidden" name="companyId" />
                                            <select class="form-control" asp-items=@ViewBag.Companies id="selectCompany">
                                                <option value="">---Şirket Seçiniz---</option>
                                            </select>

                                        </div>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <div class="mb-1">
                                            <label class="form-label" for="basicSelect">Ürün</label>

                                            <input id="productId" type="hidden" name="productId" asp-for="ProductId" />
                                            <select class="form-control" asp-items=@ViewBag.Products id="selectProduct">
                                                <option value="">---Ürün Seçiniz---</option>
                                            </select>

                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <input id="productId" type="hidden" name="productId" asp-for="ProductId" />
                                }




                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label">Başlık</label>
                                        <input type="text" id="title" class="form-control" placeholder="Başlık" asp-for="Title">
                                    </div>
                                </div>

                                <div class="col-md-6 col-12">
                                    <div class="mb-1">
                                        <label class="form-label">Metin</label>
                                        <input type="text" id="text" class="form-control" placeholder="Metin" asp-for="Text">
                                    </div>
                                </div>

                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary me-1 waves-effect waves-float waves-light">Gönder</button>
                                    <button type="reset" class="btn btn-outline-secondary waves-effect">Formu Temizle</button>
                                </div>

                            </div>


                        </form>
                    </div>
                </div>
                <div><br /></div>
            </div>
        </div>
    </div>
</section>


@section Scripts{
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $("#selectSubType").prop("disabled", true);
        $("#selectType").change(function () {
            console.log($("#selectType").val());
            if($("#selectType").val() == 1){
                $("#selectSubType").prop("disabled", false);
            }
            else{
                $("#selectSubType").val("");
                $("#selectSubType").prop("disabled", true);
            }
        });
    });

    $(document).ready(function () {
        $.ajax({
            url: '@Url.Action("Sector", "Lookup")',
            type: "GET",
            success: function (json, textStatus) {
                json = json || {};
                for (var i = 0; i < json.length; i++) {
                    $("#selectSector").append(`<option value="${json[i].id}">${json[i].name}</option>`);
                }
            },
            error: function () {
                alert("Data Not Found");
            }
        });
    });

    $(document).ready(function () {
        $("#selectCompany").prop("disabled", true);
        $("#selectSector").change(function () {

            $("#selectCompany").val("");
            $("input[name=companyId]").val("");

            $("#selectProduct").val("");
            $("input[name=productId]").val("");

            var id = $("#selectSector").val();
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("Company", "Lookup")',
                data: { "id": id },
                success: function (json, textStatus) {
                    $("#selectCompany").empty();
                    $("#selectCompany").append(`<option value="">---Şirket Seçiniz---</option>`);
                    json = json || {};
                    for (var i = 0; i < json.length; i++) {
                        $("#selectCompany").append(`<option value="${json[i].id}">${json[i].name}</option>`);
                    }
                    $("#selectCompany").prop("disabled", false);
                },
                error: function () {
                    alert("Data Not Found");
                }
            });
        });
    });

    $(document).ready(function () {
        $("#selectProduct").prop("disabled", true);
        $("#selectCompany").change(function () {

            $("#selectProduct").val("");
            $("input[name=productId]").val("");

            var id = $("#selectCompany").val();
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("Product", "Lookup")',
                data: { "id": id },
                success: function (json, textStatus) {
                    $("#selectProduct").empty();
                    $("#selectProduct").append(`<option value="">---Ürün Seçiniz---</option>`);
                    json = json || {};
                    for (var i = 0; i < json.length; i++) {
                        $("#selectProduct").append(`<option value="${json[i].id}">${json[i].name}</option>`);
                    }
                    $("#selectProduct").prop("disabled", false);
                },
                error: function () {
                    alert("Data Not Found");
                }
            });
        });
    });

</script>


<script>
    $(document).ready(function () {

        $('.form-select').select2();

        var url = '@Url.Action("LoadFeedback", "Feedback")';

        function getModelObject() {
            return {
                TitleQuery: $("#title").val(),
                SectorId: $("#sectorId").val(),
                CompanyId: $("#companyId").val(),
                ProductId: $("#productId").val(),
                TypeId: $("#typeId").val(),
                PageNumber : $("#pageNumber").val(),
                SortColumn :  $("#sortColumn").val(),
                IsAscending :  $("#isAscending").val(),
                ObjectsPerPage : 12
            }
        }

        function getData() {
            return JSON.stringify(getModelObject());
        }

        function clearFeedbackArea () {
            $("#viewAllFeedback").empty();
        }

        function callLoadFeedback() {
            $.ajax({
                type: "Post",
                url: url,
                contentType: "application/json",
                data: getData(),
                dataType: "text",
                success: function (result) {
                    $("#viewAllFeedback").append(result);
                },
                error: function(xhr, status, error) {
                    alert("Daha fazla geribildirim bulunamadı!");
                }
            });
        }

        function incrementPageNumber() {
            var currentPageNumber = parseInt($("input[name=pageNumber]").val());
            $("input[name=pageNumber]").val(currentPageNumber + 1);
        }

        function resetPageNumber() {
            $("input[name=pageNumber]").val(1);
        }

        function refreshSearch() {
            clearFeedbackArea();
            resetPageNumber();
            callLoadFeedback();
        }

        $('#loadMoreFeedback').click(function () {
            incrementPageNumber();
            callLoadFeedback();
        });

        $('#submitSearchInput').click(function () {
            refreshSearch();
        });

        $("body").on("change", "#selectSector", function () {
            $("input[name=sectorId]").val($(this).find("option:selected").val());
        });

        $("body").on("change", "#selectCompany", function () {
            $("input[name=companyId]").val($(this).find("option:selected").val());
        });

        $("body").on("change", "#selectProduct", function () {
            $("input[name=productId]").val($(this).find("option:selected").val());
        });

        $("body").on("change", "#selectType", function () {
            $("input[name=typeId]").val($(this).find("option:selected").val());
        });


    });
</script>
}